cmake_minimum_required(VERSION 3.16)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TARGET_SYSROOT $ENV{HOME}/rpi/sysroot)
set(TOOLS $ENV{HOME}/rpi/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf)
set(SYSLIBPATH ${TARGET_SYSROOT}/usr/lib/arm-linux-gnueabihf)

#set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)

#set(CMAKE_FIND_ROOT_PATH ${TARGET_SYSROOT})
#set(CMAKE_SYSROOT_LINK ${TARGET_SYSROOT})
#set(CMAKE_SYSROOT ${TARGET_SYSROOT})

set(CMAKE_C_COMPILER ${TOOLS}/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${TOOLS}/bin/arm-linux-gnueabihf-g++)

#set(CMAKE_C_FLAGS "")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -pthread")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath-link,${SYSLIBPATH}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --sysroot=${TARGET_SYSROOT}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath,'$ORIGIN'")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)